name: CI Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Run API tests
        run: |
          poetry install
          cp test/test_data.sqlite ./db.sqlite
          poetry run pytest